--- 
services: 
  mysql: 
    environment: 
      MYSQL_DATABASE: wordpress
      MYSQL_PASSWORD: wordpress
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: wordpress
    image: mysql
    ports: "3306:3306/tcp"
    stdin_open: true
    tty: true
  wordpress: 
    environment: 
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_USER: wordpress
    image: wordpress
    links: "mysql:mysql"
    ports: "8080:80/tcp"
    stdin_open: true
    tty: true
version: "2"
